[project]
name = "qemcmc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "algorithms>=0.1.4",
    "collections-extended>=2.0.2",
    "joblib>=1.5.0",
    "matplotlib>=3.10.3",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "pip>=25.1.1",
    "pytest>=8.3.5",
    "qiskit==1.4",
    "qiskit-aer>=0.17.0",
    "spyder-kernels==2.4",
    "tqdm>=4.67.1",
    "typing-extensions>=4.13.2",
]

[tool.hatch.build.targets.wheel]
      packages = ["src/qemcmc"]

[project.scripts]
qemcmc = "qemcmc:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.workspace]
members = [
    "cmake",
]
